### PR TITLE
Bug in form translations

### LINKED ISSUE #578: Bug in form translations
Forms are not translated for Bahasa i.e. the forms are launching in English instead of Bahasa. Could this be related to how the language switcher works?

Also, the patient history questions are not showing in Bahasa as they should.

### PR DESCRIPTION
**Pull request by syedowaisali90**
Hi, @vincent-karuri I have created a PR for review.
Close #578

### CODE REVIEW

File: rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/CustomRDTCaptureActivityTest.java [hunk 1]
```diff
@@ -68,6 +69,8 @@ public void setUp() {
     public void testOnCreateShouldCorrectlyInitializeActivity() {
         Utils.showProgressDialog(R.string.please_wait_title, R.string.please_wait_message, customRDTCaptureActivity);
         controller.create();
+        RDTApplication.getInstance().getSharedPreferences().saveLanguagePreference(BuildConfig.LOCALE);
+        io.ona.rdt.util.Utils.updateLocale(customRDTCaptureActivity);
         assertEquals(new Locale(BuildConfig.LOCALE).getLanguage(), customRDTCaptureActivity
```
Comment (vincent-karuri) [inline rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/CustomRDTCaptureActivityTest.java:74]: Do we need to do this? Would saving language preference before launching the activity suffice?

File: rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/LoginActivityTest.java [hunk 2]
```diff
@@ -117,6 +117,8 @@ public void testUpdateFTSDetailShouldUpdateCorrectDetails() {
 
     @Test
     public void testLocaleShouldMatchTheBuildConfigLocale() {
+        RDTApplication.getInstance().getSharedPreferences().saveLanguagePreference(BuildConfig.LOCALE);
+        Utils.updateLocale(loginActivity);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/LoginActivityTest.java:121]: https://github.com/onaio/rdt-standard/pull/579/files#r509264679

File: rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/PatientProfileActivityTest.java [hunk 3]
```diff
@@ -59,6 +61,8 @@ public void setUp() {
 
     @Test
     public void testOnCreateShouldCorrectlyInitializeActivity() {
+        RDTApplication.getInstance().getSharedPreferences().saveLanguagePreference(BuildConfig.LOCALE);
+        Utils.updateLocale(patientProfileActivity);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/PatientProfileActivityTest.java:65]: https://github.com/onaio/rdt-standard/pull/579/files#r509264679

File: rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/PatientRegisterActivityTest.java [hunk 4]
```diff
@@ -74,6 +76,8 @@ public void testOnRequestPermissionsResultShouldAlertPermissionsAreRequiredIfDen
 
     @Test
     public void testOnCreateShouldCorrectlyInitializeActivity() {
+        RDTApplication.getInstance().getSharedPreferences().saveLanguagePreference(BuildConfig.LOCALE);
+        Utils.updateLocale(patientRegisterActivity);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/PatientRegisterActivityTest.java:80]: https://github.com/onaio/rdt-standard/pull/579/files#r509264679

File: rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/RDTExpirationActivityTest.java [hunk 5]
```diff
@@ -46,6 +47,8 @@ public void setUp() {
 
     @Test
     public void testOnCreateShouldCorrectlyInitializeActivity() {
+        RDTApplication.getInstance().getSharedPreferences().saveLanguagePreference(BuildConfig.LOCALE);
+        Utils.updateLocale(rdtExpirationDateActivity);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/RDTExpirationActivityTest.java:51]: https://github.com/onaio/rdt-standard/pull/579/files#r509264679

File: rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/RDTJsonFormActivityTest.java [hunk 6]
```diff
@@ -45,6 +46,8 @@ public void setUp() throws Exception {
 
     @Test
     public void testOnCreateShouldCorrectlyInitializeActivity() {
+        RDTApplication.getInstance().getSharedPreferences().saveLanguagePreference(BuildConfig.LOCALE);
+        Utils.updateLocale(rdtJsonFormActivity);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/RDTJsonFormActivityTest.java:50]: https://github.com/onaio/rdt-standard/pull/579/files#r509264679

File: rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/CustomRDTCaptureActivityTest.java (hunk 1 above)
Comment (vincent-karuri) [reply rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/CustomRDTCaptureActivityTest.java:74]: You can save this preference as part of `ActivityRobolectricTest` set up.

File: rdt-open-reader/src/covidIndonesia/res/values-in/strings.xml [hunk 7]
```diff
@@ -5,4 +5,18 @@
...
+    <string name="no_data_available">Tidak ada data yang tersedia</string>
+    <string name="covid_barcode_product_id">ID Produk</string>
+    <string name="covid_barcode_serial_no">Nomor seri</string>
+    <string name="covid_barcode_additional_id">ID tambahan</string>
+    <string name="covid_barcode_lot_no">Lot</string>
+    <string name="covid_barcode_expiration_date">Tanggal habis tempo</string>
+    <string name="covid_barcode_is_sensor_triggered">Sensor panas dipicu</string>
+    <string name="sensor_activated">Status: Sensor Diaktifkan</string>
+    <string name="sensor_status_ok">Status: Oke</string>
+    <string name="no_barcode_captured_err">Harap tangkap kode batang untuk melanjutkan!</string>
```
Comment (vincent-karuri) [inline rdt-open-reader/src/covidIndonesia/res/values-in/strings.xml:21]: Why do we need these translations?

File: rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/CustomRDTCaptureActivityTest.java (hunk 1 above)
Comment (syedowaisali90) [reply rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/CustomRDTCaptureActivityTest.java:74]: > Do we need to do this? Would saving language preference before launching the activity suffice?

yes we need to save this before the assertion because by default `en` will be returned by `SharedPreference` that's why we need to do this

Comment (syedowaisali90) [reply rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/CustomRDTCaptureActivityTest.java:74]: > You can save this preference as part of `ActivityRobolectricTest` set up.

yes it could be

File: rdt-open-reader/src/covidIndonesia/res/values-in/strings.xml (hunk 7 above)
Comment (vincent-karuri) [reply rdt-open-reader/src/covidIndonesia/res/values-in/strings.xml:21]: The patient history questions are not affected by this.

File: rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidPatientRegisterActivity.java [hunk 8]
```diff
@@ -72,7 +76,8 @@ private void languageSwitcherDialog() {
         AlertDialog.Builder builder = new AlertDialog.Builder(this);
         builder.setTitle(getResources().getString(R.string.drawer_menu_item_change_language));
         builder.setSingleChoiceItems(R.array.locales_key, selectedLanguageIndex, (dialog, position) -> {
-            LangUtils.saveLanguage(getApplication(), localesVal[position]);
+            allSharedPreferences.saveLanguagePreference(localesVal[position]);
+            Utils.updateLocale(CovidPatientRegisterActivity.this);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidPatientRegisterActivity.java:80]: You can use the `NativeFormLangUtils` to update the app locale on native forms.

File: rdt-open-reader/src/main/java/io/ona/rdt/application/RDTApplication.java [hunk 9]
```diff
@@ -147,4 +149,11 @@ public ParasiteProfileRepository getParasiteProfileRepository() {
         }
         return parasiteProfileRepository;
     }
+
+    public com.vijay.jsonwizard.utils.AllSharedPreferences getSharedPreferences() {
+        if (sharedPreferences == null) {
+            sharedPreferences = new com.vijay.jsonwizard.utils.AllSharedPreferences(PreferenceManager.getDefaultSharedPreferences(this));
+        }
+        return sharedPreferences;
+    }
```
Comment (vincent-karuri) [inline rdt-open-reader/src/main/java/io/ona/rdt/application/RDTApplication.java:158]: https://github.com/onaio/rdt-standard/pull/579/files#r509273247

File: rdt-open-reader/src/main/java/io/ona/rdt/util/Utils.java [hunk 10]
```diff
@@ -104,7 +102,7 @@ public static int convertDpToPixels(Context context, float dp) {
 
     public static void updateLocale(Context context) {
 
-        String savedLocale = RDTApplication.getInstance().getContext().allSharedPreferences().getPreference(Constants.Locale.LOCALE);
+        String savedLocale = RDTApplication.getInstance().getSharedPreferences().fetchLanguagePreference();
```
Comment (vincent-karuri) [inline rdt-open-reader/src/main/java/io/ona/rdt/util/Utils.java:105]: https://github.com/onaio/rdt-standard/pull/579/files#r509273247

File: rdt-open-reader/src/test/java/io/ona/rdt/util/UtilsTest.java [hunk 11]
```diff
@@ -198,5 +198,9 @@ private void mockStaticClasses() {
         doReturn(FALSE).when(allSharedPreferences).getPreference(IS_IMG_SYNC_ENABLED);
         doReturn(BuildConfig.LOCALE).when(allSharedPreferences).getPreference(Constants.Locale.LOCALE);
         doReturn(allSharedPreferences).when(drishtiContext).allSharedPreferences();
+
+        com.vijay.jsonwizard.utils.AllSharedPreferences mAllSharedPreferences = mock(com.vijay.jsonwizard.utils.AllSharedPreferences.class);
+        doReturn(BuildConfig.LOCALE).when(mAllSharedPreferences).fetchLanguagePreference();
+        PowerMockito.when(rdtApplication.getSharedPreferences()).thenReturn(mAllSharedPreferences);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/test/java/io/ona/rdt/util/UtilsTest.java:204]: https://github.com/onaio/rdt-standard/pull/579/files#r509273247

File: rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java [hunk 12]
```diff
@@ -72,15 +76,18 @@ public void testLanguageSwitcherDialogShouldSetCorrectLocale() throws Exception
...
     @Test
     public void testRegisterLanguageSwitcherShouldVerifyLocaleIndex() throws Exception {
-        verifySavedLanguageIndex(1);
-        LangUtils.saveLanguage(covidPatientRegisterActivity, locales[0]);
         verifySavedLanguageIndex(0);
+        Resources resources = covidPatientRegisterActivity.getResources();
+        Configuration configuration = resources.getConfiguration();
+        configuration.setLocale(new Locale(locales[1]));
+        resources.updateConfiguration(configuration, resources.getDisplayMetrics());
+        verifySavedLanguageIndex(1);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java:90]: Not sure I understand what this is testing? Is this meant to verify that the default language is selected?

File: rdt-open-reader/src/covidIndonesia/res/values-in/strings.xml (hunk 7 above)
Comment (syedowaisali90) [reply rdt-open-reader/src/covidIndonesia/res/values-in/strings.xml:21]: removed.

File: rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidPatientRegisterActivity.java (hunk 8 above)
Comment (syedowaisali90) [reply rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidPatientRegisterActivity.java:80]: used `LangUtils.class`

File: rdt-open-reader/src/main/java/io/ona/rdt/application/RDTApplication.java (hunk 9 above)
Comment (syedowaisali90) [reply rdt-open-reader/src/main/java/io/ona/rdt/application/RDTApplication.java:158]: removed.

File: rdt-open-reader/src/main/java/io/ona/rdt/util/Utils.java (hunk 10 above)
Comment (syedowaisali90) [reply rdt-open-reader/src/main/java/io/ona/rdt/util/Utils.java:105]: updated.

File: rdt-open-reader/src/test/java/io/ona/rdt/util/UtilsTest.java (hunk 11 above)
Comment (syedowaisali90) [reply rdt-open-reader/src/test/java/io/ona/rdt/util/UtilsTest.java:204]: updated.

File: rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/CustomRDTCaptureActivityTest.java (hunk 1 above)
Comment (vincent-karuri) [reply rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/CustomRDTCaptureActivityTest.java:73]: You can add a `@Before` method that all the child classes invoke.

File: rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidPatientRegisterActivity.java (hunk 8 above)
Comment (vincent-karuri) [reply rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidPatientRegisterActivity.java]: Does that work?

Comment (vincent-karuri) [reply rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidPatientRegisterActivity.java]: Are the forms translated now?

File: rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/PatientRegisterActivityTest.java [hunk 13]
```diff
@@ -74,6 +76,7 @@ public void testOnRequestPermissionsResultShouldAlertPermissionsAreRequiredIfDen
 
     @Test
     public void testOnCreateShouldCorrectlyInitializeActivity() {
+        LangUtils.saveLanguage(patientRegisterActivity, BuildConfig.LOCALE);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/test/java/io/ona/rdt/robolectric/activity/PatientRegisterActivityTest.java:79]: This is repeated for all Activity tests, you can do this instead https://github.com/onaio/rdt-standard/pull/579/files#r509921665.

File: rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java [hunk 14]
```diff
@@ -72,15 +77,15 @@ public void testLanguageSwitcherDialogShouldSetCorrectLocale() throws Exception
 
     private void verifyLocaleIsSaved(ListView listView, int position, String locale) {
         listView.performItemClick(null, position, listView.getItemIdAtPosition(position));
-        Assert.assertEquals(locale, LangUtils.getLanguage(RDTApplication.getInstance()));
-        Assert.assertEquals(locale, RDTApplication.getInstance().getResources().getConfiguration().locale.getLanguage());
+        Assert.assertEquals(locale, new Locale(LangUtils.getLanguage(covidPatientRegisterActivity)).getLanguage());
```
Comment (vincent-karuri) [inline rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java:80]: `Assert.assertEquals(locale, RDTApplication.getInstance().getResources().getConfiguration().locale.getLanguage());` is also a valid check, please revert it.

Comment (vincent-karuri) [reply rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java:80]: Also, shouldn't this be `Assert.assertEquals(locale, LangUtils.getLanguage(covidPatientRegisterActivity));`?

File: rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java [hunk 15]
```diff
@@ -72,15 +77,15 @@ public void testLanguageSwitcherDialogShouldSetCorrectLocale() throws Exception
...
     }
 
     @Test
     public void testRegisterLanguageSwitcherShouldVerifyLocaleIndex() throws Exception {
-        verifySavedLanguageIndex(1);
-        LangUtils.saveLanguage(covidPatientRegisterActivity, locales[0]);
         verifySavedLanguageIndex(0);
+        LangUtils.saveLanguage(covidPatientRegisterActivity, BuildConfig.LOCALE);
+        Utils.updateLocale(covidPatientRegisterActivity);
+        verifySavedLanguageIndex(1);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java:88]: What does this test?

File: rdt-open-reader/src/test/java/io/ona/rdt/util/UtilsTest.java [hunk 16]
```diff
@@ -198,5 +200,9 @@ private void mockStaticClasses() {
         doReturn(FALSE).when(allSharedPreferences).getPreference(IS_IMG_SYNC_ENABLED);
         doReturn(BuildConfig.LOCALE).when(allSharedPreferences).getPreference(Constants.Locale.LOCALE);
         doReturn(allSharedPreferences).when(drishtiContext).allSharedPreferences();
+
+        mockStatic(LangUtils.class);
+        PowerMockito.doNothing().when(LangUtils.class);
+        LangUtils.saveLanguage(ArgumentMatchers.any(Context.class), ArgumentMatchers.anyString());
```
Comment (vincent-karuri) [inline rdt-open-reader/src/test/java/io/ona/rdt/util/UtilsTest.java:206]: This can be merged to one line. i.e. `when(LangUtils.class, "saveLanguage"...)`.

File: rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java (hunk 15 above)
Comment (syedowaisali90) [reply rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java:88]: if we call a method `Langutils.saveLanguage` inside this method it does update the `resources.updateConfiguration(configuration, resources.getDisplayMetrics());` that's why i have called the method `Utils.updateLocale`.

If we call a method `RDTApplication.getInstance().getResources().getConfiguration().locale.getLanguage()` after `LangUtils.saveLanguage` it returns a previous locale not updated locale.

File: rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java (hunk 14 above)
Comment (syedowaisali90) [reply rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java:80]: if I will revert this method so I will need to call the `Utils.updateLocale` method. https://github.com/onaio/rdt-standard/pull/579#discussion_r509976237

File: rdt-open-reader/src/test/java/io/ona/rdt/util/UtilsTest.java (hunk 16 above)
Comment (syedowaisali90) [reply rdt-open-reader/src/test/java/io/ona/rdt/util/UtilsTest.java:206]: fixed.

File: rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidPatientRegisterActivity.java [hunk 17]
```diff
@@ -72,7 +73,7 @@ private void languageSwitcherDialog() {
         AlertDialog.Builder builder = new AlertDialog.Builder(this);
         builder.setTitle(getResources().getString(R.string.drawer_menu_item_change_language));
         builder.setSingleChoiceItems(R.array.locales_key, selectedLanguageIndex, (dialog, position) -> {
-            LangUtils.saveLanguage(getApplication(), localesVal[position]);
+            LangUtils.saveLanguage(RDTApplication.getInstance(), localesVal[position]);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidPatientRegisterActivity.java:76]: This can be reverted.

File: rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java [hunk 18]
```diff
@@ -72,14 +76,14 @@ public void testLanguageSwitcherDialogShouldSetCorrectLocale() throws Exception
...
-        Assert.assertEquals(locale, RDTApplication.getInstance().getResources().getConfiguration().locale.getLanguage());
+        Assert.assertEquals(locale, new Locale(LangUtils.getLanguage(covidPatientRegisterActivity)).getLanguage());
     }
 
     @Test
     public void testRegisterLanguageSwitcherShouldVerifyLocaleIndex() throws Exception {
         verifySavedLanguageIndex(1);
-        LangUtils.saveLanguage(covidPatientRegisterActivity, locales[0]);
+        LangUtils.saveLanguage(covidPatientRegisterActivity, "en");
+        Utils.updateLocale(covidPatientRegisterActivity);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java:86]: If this test is supposed to verify the default language is set then I don't think we need this block. We should simply have one call to `verifySavedLanguageIndex(i);`

File: rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java (hunk 14 above)
Comment (vincent-karuri) [reply rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java:79]: I don't think that will be necessary. You should be able to simply revert the changes and the test should pass since what was there before is the expected behaviour.

**Comment by vincent-karuri** [comment]
Could we make Bahasa the default language in the language switcher?

**Comment by syedowaisali90** [comment]
> Could we make Bahasa the default language in the language switcher?

we make this but the problem is `LangUtils.getLanguage` method return "en" by default

File: rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidPatientRegisterActivity.java (hunk 17 above)
Comment (syedowaisali90) [reply rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidPatientRegisterActivity.java:76]: done

File: rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java (hunk 18 above)
Comment (syedowaisali90) [reply rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java:86]: if I remove the above code snippet so I can only verify the default locale index but if I need to verify another locale index then I need to update the locale first.

Comment (vincent-karuri) [reply rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java:86]: Ok, we can keep it. Is there a reason "en" is hard-coded now instead of using `locales` array like before?

Comment (syedowaisali90) [reply rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java]: removed hardcoded locale and get from the resource file

**Comment by vincent-karuri** [comment]
> > Could we make Bahasa the default language in the language switcher?
> 
> we make this but the problem is `LangUtils.getLanguage` method return "en" by default

Do we know why that is? Isn't it possible to save a different default language?

**Comment by syedowaisali90** [comment]
> > > Could we make Bahasa the default language in the language switcher?
> > 
> > 
> > we make this but the problem is `LangUtils.getLanguage` method return "en" by default
> 
> Do we know why that is? Isn't it possible to save a different default language?

Since LangUtils return `en` locale by default so ff we want to get `id` locale by default so we need to update the locale on the first install.

Does this make sense?

**Comment by vincent-karuri** [comment]
> > > > Could we make Bahasa the default language in the language switcher?
> > > 
> > > 
> > > we make this but the problem is `LangUtils.getLanguage` method return "en" by default
> > 
> > 
> > Do we know why that is? Isn't it possible to save a different default language?
> 
> Since LangUtils return `en` locale by default so ff we want to get `id` locale by default so we need to update the locale on the first install.
> 
> Does this make sense?

You can do it how we had it initially where you get the default value from the buildconfig if it is not already set in the LangUtils (i.e. on fresh install). On subsequent launches, if the LangUtils value is already set, then we use it instead.

File: rdt-open-reader/src/main/java/io/ona/rdt/application/RDTApplication.java [hunk 19]
```diff
@@ -68,6 +70,11 @@ public void onCreate() {
         if (sharedPreferences.getPreference(IS_IMG_SYNC_ENABLED).isEmpty()) {
             sharedPreferences.savePreference(IS_IMG_SYNC_ENABLED, String.valueOf(true));
         }
+
+        // set locale initially
+        if (sharedPreferences.getPreference(Constants.Locale.LOCALE).isEmpty()) {
+            sharedPreferences.savePreference(Constants.Locale.LOCALE, BuildConfig.LOCALE);
+        }
```
Comment (vincent-karuri) [inline rdt-open-reader/src/main/java/io/ona/rdt/application/RDTApplication.java:77]: Why not check this through `LangUtils`?

Comment (syedowaisali90) [reply rdt-open-reader/src/main/java/io/ona/rdt/application/RDTApplication.java:77]: LangUtils return `en` by default that why I didn't use that

Comment (vincent-karuri) [reply rdt-open-reader/src/main/java/io/ona/rdt/application/RDTApplication.java:77]: Ok, use `AllConstants.LANGUAGE_PREFERENCE_KEY` then to make it uniform with the core library key for that preference.

Also, use `StringUtils.isEmpty(sharedPreferences.getPreference(AllConstants.LANGUAGE_PREFERENCE_KEY`))` instead, which is a safer check in case of NPE.

File: rdt-open-reader/src/main/java/io/ona/rdt/application/RDTApplication.java [hunk 20]
```diff
@@ -68,6 +72,11 @@ public void onCreate() {
         if (sharedPreferences.getPreference(IS_IMG_SYNC_ENABLED).isEmpty()) {
             sharedPreferences.savePreference(IS_IMG_SYNC_ENABLED, String.valueOf(true));
         }
+
+        // set locale initially
+        if (StringUtils.isEmpty(sharedPreferences.getPreference(AllConstants.LANGUAGE_PREFERENCE_KEY))) {
+            sharedPreferences.savePreference(Constants.Locale.LOCALE, BuildConfig.LOCALE);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/main/java/io/ona/rdt/application/RDTApplication.java:78]: The key here also needs to change to `AllConstants.LANGUAGE_PREFERENCE_KEY`.

File: rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java (hunk 14 above)
Comment (syedowaisali90) [reply rdt-open-reader/src/testCovidIndonesia/java/io/ona/rdt/robolectric/activity/CovidPatientRegisterActivityTest.java:79]: changes reverted

File: rdt-open-reader/src/main/java/io/ona/rdt/application/RDTApplication.java (hunk 20 above)
Comment (syedowaisali90) [reply rdt-open-reader/src/main/java/io/ona/rdt/application/RDTApplication.java:78]: Done

**Review by vincent-karuri — APPROVED** [review]
