### PR TITLE
Bugs exist on sample collection patient information confirmation screen

### LINKED ISSUE #469: Bugs exist on sample collection patient information confirmation screen
3 bugs exist on patient collection confirmation screen:

- [x] 1. Patient Dob showing up as null
- [x] 2. Unable to continue forward even when both checkboxes are checked
- [ ] Sample ID field is missing

image

### PR DESCRIPTION
**Pull request by syedowaisali90**
Hi @vincent-karuri I have created a PR for review.
Close #469

### CODE REVIEW

File: rdt-open-reader/src/main/java/io/ona/rdt/fragment/RDTJsonFormFragment.java [hunk 1]
```diff
@@ -231,4 +257,23 @@ public RDTJsonFormActivity getRdtActivity() {
...
+                        uniqueId = value;
+                    }
+                }
+            }
+        } catch (JSONException ex) {
+            Timber.e(ex);
+        }
+
+        return uniqueId;
+    }
```
Comment (vincent-karuri) [inline rdt-open-reader/src/main/java/io/ona/rdt/fragment/RDTJsonFormFragment.java:278]: Is this supposed to write the barcode sample id to the confirmation screen? If so, this can be achieved by using the `jsonApi` https://github.com/onaio/rdt-standard/blob/b276a520f238cf907e90742a7d4dfe9fa0d54b71/rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/widget/CovidRDTBarcodeFactory.java#L69.

Get the step to write into from the step state config.

File: rdt-open-reader/src/main/java/io/ona/rdt/fragment/RDTJsonFormFragment.java [hunk 2]
```diff
@@ -45,6 +50,27 @@
...
+                            JSONObject option = field.getJSONArray(JsonFormConstants.OPTIONS_FIELD_NAME).getJSONObject(0);
+                            option.put(JsonFormConstants.TEXT, uniqueId);
+                        }
+                    }
+                }
+            }
+
+        } catch (JSONException ex) {
+            Timber.e(ex);
+        }
```
Comment (vincent-karuri) [inline rdt-open-reader/src/main/java/io/ona/rdt/fragment/RDTJsonFormFragment.java:73]: Is this logic to add the unique id to the patient info confirmation page? I think there's a easier way to do it within the onescan barcode factory. 

Will push a commit to address this.

File: rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/widget/CovidRDTBarcodeFactory.java [hunk 3]
```diff
@@ -67,6 +71,13 @@ protected void populateRelevantFields(String[] individualVals) throws JSONExcept
         jsonApi.writeValue(stepName, LOT_NO, individualVals[2],  "", "", "", false);
         jsonApi.writeValue(stepName, GTIN, individualVals[3],  "", "", "", false);
         jsonApi.writeValue(stepName, TEMP_SENSOR, individualVals[SENSOR_TRIGGER_INDEX],  "", "", "", false);
+
+        // write unique id to confirmation page
+        String patientInfoConfirmationPage = stepStateConfig.optString(CovidConstants.Step.COVID_SAMPLE_COLLECTION_FORM_PATIENT_INFO_CONFIRMATION_PAGE);
+        JSONObject uniqueIdCheckBox = RDTJsonFormUtils.getField(patientInfoConfirmationPage,
+                        CovidConstants.FormFields.PATIENT_INFO_UNIQUE_ID,
+                        widgetArgs.getContext());
+        CovidRDTJsonFormUtils.fillPatientData(uniqueIdCheckBox, individualVals[0]);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/widget/CovidRDTBarcodeFactory.java:80]: Writing unique id to form checkbox field.

File: rdt-open-reader/src/main/java/io/ona/rdt/fragment/RDTJsonFormFragment.java (hunk 2 above)
Comment (vincent-karuri) [reply rdt-open-reader/src/main/java/io/ona/rdt/fragment/RDTJsonFormFragment.java]: https://github.com/onaio/rdt-standard/pull/506/commits/0143e849e2a865e5f47d7b961afbb391ad3b5831#r490127702

File: rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/interactor/CovidPatientRegisterActivityInteractor.java [hunk 4]
```diff
@@ -45,13 +45,16 @@ protected Patient createPatient(String baseEntityId, JSONArray formFields) {
         String firstName = getStrField(formFields, CovidConstants.FormFields.PATIENT_FIRST_NAME);
         String lastName = getStrField(formFields, CovidConstants.FormFields.PATIENT_LAST_NAME);
         String sex = getStrField(formFields, Constants.DBConstants.SEX);
+        String patientAge = getStrField(formFields, Constants.DBConstants.AGE);
+        patientAge = StringUtils.isBlank(patientAge) ? "0" : patientAge;
+        String dob = getStrField(formFields, Constants.DBConstants.DOB);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/interactor/CovidPatientRegisterActivityInteractor.java:50]: This class extends `PatientRegisterActivityInteractor` so this code is duplicated.

Could you maybe refactor this method so that the fields with equal values can be populated once in a protected method that can be called in each class?

i.e. `populateCommonPatientFields(Patient patient, JsonArray formFields)` and age, sex and dob can be populated here.

**Review by vincent-karuri — APPROVED** [review]
