### PR TITLE
Crashes on Android 10 

### LINKED ISSUE #950: Crashes on Android 10
It happened on the freshly installed APK on 3 devices: 1 Samsung A50s and 2 Samsung A21.

How I get the crashes:
1. Installed the APK
2. Waiting to sync
3. Click one of the patients
4. Click RDT Form
5. Click Locate Me
6. Click Continue until the page of Which RDT?
7. Click the barcode scanning option
8. Scanning the barcode (After getting caught, sometimes the screen appeared twice after being scanned)
9. Status: OK page appeared, click continue
10. White page appeared with RDT written on the top of the page

Other crashes:
1. It successfully scanned until the capturing image page appeared
2. After capturing the image, white page appeared with RDT written on the top of the page

The video is here:
https://drive.google.com/file/d/105Qzc-QyJzYY7u9t64PivP49yD0lCgFP/view?usp=sharing

@yussin-hidayat @vincent-karuri @mwkhan1983 @syedowaisali90

### PR DESCRIPTION
**Pull request by syedowaisali90**
close #950

### CODE REVIEW

File: rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java [hunk 1]
```diff
@@ -65,10 +65,7 @@ protected void onActivityResult(int requestCode, int resultCode, @Nullable Inten
             // for exceptions thrown and caught during widget instantiation
             Bundle bundle = data.getExtras();
             throw  (RuntimeException) bundle.getSerializable(JsonFormConstants.RESULT_INTENT.RUNTIME_EXCEPTION);
-        } else if (requestCode == REQUEST_CODE_GET_JSON && resultCode == RESULT_CANCELED) {
```
Comment (vincent-karuri) [inline rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: This is required to close out the app when the jsonformactivity crashes.

Comment (vincent-karuri) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: Also, how is this changed related to #950?

Comment (syedowaisali90) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: > This is required to close out the app when the jsonformactivity crashes.

I have checked the toast showing if we do not allow the location permission.

> Also, how is this changed related to #950?

yussin has shared the log https://github.com/onaio/rdt-standard/issues/950#issuecomment-816337260 and in the log the is related to this line.

Comment (vincent-karuri) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: this line should only run if the result code is `RESULT_CANCELED`. If permissions are rejected, could you set the result code to something else?

Comment (syedowaisali90) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: I think we don't need to check something else because toast is already showing.

Comment (vincent-karuri) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: What toast are you referring to?

Comment (vincent-karuri) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: my suggestion is to change this line https://github.com/onaio/rdt-standard/blob/a546608c8d1fb5f101d3d175231cfb1af2afb716/rdt-open-reader/src/main/java/io/ona/rdt/activity/RDTJsonFormActivity.java#L74 to a different status other that `RESULT_CANCELED`. If the issue is around permissions being rejected.

Comment (syedowaisali90) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: > What toast are you referring to?

https://github.com/onaio/rdt-standard/blob/a546608c8d1fb5f101d3d175231cfb1af2afb716/rdt-open-reader/src/main/java/io/ona/rdt/activity/RDTJsonFormActivity.java#L75

Comment (syedowaisali90) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: Even i changed the status but there is nothing have to do so, i think we remove `setResult(RESULT_CANCELED, null);` this

Comment (vincent-karuri) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: does that work? what is the value of `resultCode` if we remove it?

Comment (syedowaisali90) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: yes, the value of resultCode is `RESULT_CANCELED`

Comment (vincent-karuri) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: what is the value if `setResult(RESULT_CANCELED, null);` was removed?

Comment (syedowaisali90) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: if we removed the `setResult(RESULT_CANCELED, null);` then the value still `RESULT_CANCELED`

Comment (vincent-karuri) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: then how would this fix the issue of crashing? wouldn't we still enter this else block?

Comment (syedowaisali90) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: Actually, I just removed the explicit crash due to the permission failure Because we are already showing the toast in case the user denies permission. So, there is no need to throw an exception.

Comment (vincent-karuri) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: My point was that the crash was not there for that purpose. We need to retain it to allow the app to close out completely in case a crash occurs from the jsonformactivity.

Currently, the only way I see to do that is to see if the result code of cancelled was returned.

Comment (vincent-karuri) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java:68]: so if cancelled is returned when we remove the line, the we can use a custom code instead and leave the else block as is.

Comment (syedowaisali90) [reply rdt-open-reader/src/main/java/io/ona/rdt/activity/PatientProfileActivity.java]: fixed.

File: rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidJsonFormActivity.java [hunk 2]
```diff
@@ -104,6 +105,7 @@ public void onRequestPermissionsResult(int requestCode, @NonNull String[] permis
         super.onRequestPermissionsResult(requestCode, permissions, grantResults);
```
Comment (vincent-karuri) [inline rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidJsonFormActivity.java:105]: We can remove this overridden method if it's the same as https://github.com/onaio/rdt-standard/pull/953/files#diff-f8f8bfc77f90eeb4ecb4cef36ec3b6020c965fc37320b8e4e63b5d3934933751R72.

File: rdt-open-reader/src/main/java/io/ona/rdt/util/Constants.java [hunk 3]
```diff
@@ -148,4 +150,8 @@
     interface Preference {
         String LOCATION_TREE = "location_tree";
     }
+
+    interface RESULT_CODE {
+        int PERMISSION_FAILED = Activity.RESULT_FIRST_USER + 1;
```
Comment (vincent-karuri) [inline rdt-open-reader/src/main/java/io/ona/rdt/util/Constants.java:155]: Cool, could we rename this to `PERMISSIONS_DENIED`?

File: rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidJsonFormActivity.java (hunk 2 above)
Comment (syedowaisali90) [reply rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidJsonFormActivity.java:105]: actually, I think we cannot remove the overridden method because the child class method checking the location permission whereas the parent class method checking the phone permission.

File: rdt-open-reader/src/main/java/io/ona/rdt/util/Constants.java (hunk 3 above)
Comment (syedowaisali90) [reply rdt-open-reader/src/main/java/io/ona/rdt/util/Constants.java]: done

File: rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidJsonFormActivity.java (hunk 2 above)
Comment (vincent-karuri) [reply rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/CovidJsonFormActivity.java:105]: cool

**Review by vincent-karuri — APPROVED** [review]

**Comment by anuraj-shankar** [comment]
Does this fix listed for #953 correct all the problems listed in #950?
